 type Query {
    hello: String!
    cats: [Cat!]!
    dogs: [Dog!]!
  }

  type Cat {
    id: ID!
    name: String!
  }

  type Dog {
    id: ID!
    name: String!
  }
  type Mutation {
    createCat(name: String!): Cat!
    createDog(name: String!): Dog!
  }